# Docker file used for the installation of the the Agent Control on k8s.

# Use official alpine images as base stages for kubectl and helm
# Automatically updated by Renovate
FROM alpine/helm:4.1.1 AS helm
FROM alpine/kubectl:1.35.0 AS kubectl

FROM debian:trixie-slim

ARG TARGETARCH

COPY --chmod=755 bin/newrelic-agent-control-k8s-cli-${TARGETARCH} /bin/newrelic-agent-control-cli

# Copy kubectl and helm from official alpine images
COPY --from=kubectl /usr/local/bin/kubectl /usr/local/bin/kubectl
COPY --from=helm /usr/bin/helm /usr/local/bin/helm

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y ca-certificates && \
    apt-get clean

# Create a home directory for nobody user and set ownership
# This is so Helm can actually run as it tries to write to the home directory
RUN mkdir -p /home/nobody && \
    chown nobody:nogroup /home/nobody

USER nobody
ENV HOME=/home/nobody

ENTRYPOINT ["/bin/newrelic-agent-control-cli"]
