name: 📞 Test agent package installation

on:
  workflow_call:
    inputs:
      TAG:
        required: true
        type: string
      PACKAGE_NAME:
        required: true
        type: string
      REPO_ENDPOINT:
        required: false
        type: string
        description: 'Repository endpoint to fetch packages from'
        default: "https://download.newrelic.com/preview"

permissions:
  contents: read

env:
  TAG: ${{ inputs.TAG }}
  REPO_ENDPOINT: ${{ inputs.REPO_ENDPOINT }}

jobs:
  molecule-test-packages:
    name: Test package installation
    runs-on: ubuntu-latest
    steps:
      - uses: newrelic/pkg-installation-testing-action@6daca2b1fba11b371c4062f204dfc150fb1589e0 # v1
        with:
          gpg_key: 'https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg'
          repo_base_url: ${{ inputs.REPO_ENDPOINT }}
          package_name: ${{ inputs.PACKAGE_NAME }}
          package_version: ${{ inputs.TAG }}
          platforms: "al2023,centos8,debian-bullseye,debian-bookworm,redhat8,redhat9,suse15.3,suse15.4,suse15.5,ubuntu2004,ubuntu2204,ubuntu2404"
