name: 📞 Onhost canaries operation

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
      operation:
        required: true
        type: string
      fleet_id:
        required: true
        type: string
      windows_fleet_id:
        required: true
        type: string
      package_version:
        required: false
        type: string
        default: ""

  workflow_call:
    secrets:
      AWS_ROLE_ARN:
        required: true
      AWS_VPC_SUBNET:
        required: true
      AC_CANARY_WINDOWS_PASSWORD:
        required: true

    inputs:
      environment:
        required: true
        type: string
      operation:
        required: true
        type: string
      fleet_id:
        required: true
        type: string
      windows_fleet_id:
        required: true
        type: string
      package_version:
        required: false
        type: string
        default: ""

permissions:
  contents: read

jobs:
  update-version:
    name: Prepare infra
    runs-on: ubuntu-latest
    permissions:
      # required to oidc AWS
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set branch name
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          # Is the ref a tag? If so, remove refs/tags/ prefix
          GIT_BRANCH="${GIT_BRANCH#refs/tags/}"
          echo "GIT_BRANCH=$GIT_BRANCH" >> "$GITHUB_ENV"

      - name: Execute operation
        uses: newrelic/fargate-runner-action@main
        with:
          aws_region: us-east-2
          container_make_target: "AC_CANARY_WINDOWS_PASSWORD=${{ secrets.AC_CANARY_WINDOWS_PASSWORD }} FLEET_ID=${{ inputs.fleet_id }} WINDOWS_FLEET_ID=${{ inputs.windows_fleet_id }} ENVIRONMENT=${{ inputs.environment }} PACKAGE_VERSION=${{ inputs.package_version }} test/onhost-canaries/terraform-${{ inputs.operation }}"
          ecs_cluster_name: agent_control
          task_definition_name: agent_control
          cloud_watch_logs_group_name: /ecs/test-prerelease-agent_control
          cloud_watch_logs_stream_name: ecs/test-agent_control
          aws_vpc_subnet: ${{ secrets.AWS_VPC_SUBNET }}
          repo_name: ${{ github.repository }}
          git_clone_url: "ssh://git@github.com/${{ github.repository }}.git"
          ref: "${{ env.GIT_BRANCH }}"
