name: 'Send Warning Notification via Slack'

on:
  workflow_call:
    inputs:
      message:
        description: 'The message to include in the Slack notification'
        required: true
        type: string

permissions:
  contents: read

jobs:
  send-slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Notify failure via Slack (AC channel)
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          webhook-type: webhook-trigger
          payload: |
            {
              "text": ":warning: [${{ inputs.message }}] @hero check <${{ env.GITHUB_JOB_URL }}>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.AC_SLACK_WEBHOOK }}
          GITHUB_JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
