name: Lint PR title

on:
  pull_request:
    types:
      - opened
      - edited

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7
        with:
          node-version: 24.14.0

      - name: Install commitlint with default config
        run: |
          npm i @commitlint/cli
          npm i @commitlint/config-conventional

      - name: Validate PR title
        run: echo '${{ github.event.pull_request.title }}' | npx commitlint --extends @commitlint/config-conventional
